[package]
name = "trilateration-rs"
version = "0.1.0"
authors = ["Calvin Cieslak <calvin.cieslak@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0.106"
serde_json = "1.0.51"
clap = {version = "~2.27.0", features = ["yaml"]}
